---
title: "gsea_viz"
author: "Kyle Campbell"
date: "3/9/2021"
output: html_document
---

```{r setup, include=FALSE}
library(here)
library(ggpubr)
library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

Read in GSEA results
```{r}
base.down <- read_tsv(here("results", "GSEA", "base_model_go_bp.GseaPreranked.1615236822173", "gsea_report_for_na_neg_1615236822173.tsv"))
base.up <- read_tsv(here("results", "GSEA", "base_model_go_bp.GseaPreranked.1615236822173", "gsea_report_for_na_pos_1615236822173.tsv"))
pc.down <- read_tsv(here("results", "GSEA", "pc_model_go_bp.GseaPreranked.1615234194720", "gsea_report_for_na_neg_1615234194720.tsv"))
pc.up <- read_tsv(here("results", "GSEA", "pc_model_go_bp.GseaPreranked.1615234194720", "gsea_report_for_na_pos_1615234194720.tsv"))
```

Select only the relevant results from the dataframes
```{r}
clean_gsea <- function(data) {
  x <- data %>%
    dplyr::select(NAME, SIZE, NES, `NOM p-val`, `FDR q-val`)
  return (x)
}

base.neg <- clean_gsea(base.down)
base.pos <- clean_gsea(base.up)

base.res <- rbind(base.pos, base.neg)

pc.neg <- clean_gsea(pc.down)
pc.pos <- clean_gsea(pc.up)

pc.res <- rbind(pc.pos, pc.neg)
```

```{r}
base.pos.hits <- base.pos %>%
  filter(`FDR q-val` < 0.05)
base.pos.hits
```
```{r}
base.neg.hits <- base.neg %>%
  filter(`FDR q-val` < 0.05)
base.neg.hits
```

```{r}
pc.neg.hits <- pc.neg %>%
  filter(`FDR q-val` < 0.05) %>%
  arrange(desc(abs(NES)))
pc.neg.hits
```

```{r}
pc.pos.hits <- pc.pos %>%
  arrange(`FDR q-val`)
  #filter(`FDR q-val` < 0.05)
pc.pos.hits
```

Graph GSEA results
```{r}
res.graph <- base.res %>% arrange(desc(abs(NES))) %>% top_n(n = 25, wt = abs(NES))

p1 <- ggplot(data = res.graph, mapping = aes(x = NES, y = NAME, size = SIZE, color = `FDR q-val`)) +
  geom_point() +
  ylab("") + xlab("Normalized Enrichment Score") + ggtitle("Base model") + geom_vline(xintercept = 0)
p1
#ggsave(here("results", "GSEA", paste0(Sys.Date(), "_gsea_base_res.png")))
```

```{r}
base.graph <- base.res %>% arrange(desc(abs(NES))) %>% slice_head(n = 25)

p1 <- ggplot(data = base.graph, mapping = aes(x = NES, y = fct_rev(fct_reorder(NAME, NES)), fill = `FDR q-val`)) +
  geom_col() +
  scale_fill_gradient2(midpoint = 0.05) +
  ylab("") + xlab("Normalized Enrichment Score") + ggtitle("Unadjusted") +
  theme_minimal(base_size = 20) + theme(title = element_text(size = 28), legend.position = "bottom", legend.text = element_text(angle = 45), axis.text.y = element_text(color = "black")) + labs(fill = "False discovery rate-adjusted q-value  ")

#theme_minimal(base_size = 20)

p1
```


```{r}
pc.graph <- pc.res %>% arrange(desc(abs(NES))) %>% slice_head(n = 25)

p2 <- ggplot(data = pc.graph, mapping = aes(x = NES, y = NAME, size = SIZE, color = `FDR q-val`)) +
  geom_point() +
  ylab("") + xlab("Normalized Enrichment Score") + ggtitle("Cell Type-adjusted") + geom_vline(xintercept = 0)
p2
#ggsave(here("results", "GSEA", paste0(Sys.Date(), "_gsea_pc_res.png")))
```

```{r}
p2 <- ggplot(data = pc.graph, mapping = aes(x = NES, y = fct_rev(fct_reorder(NAME, NES)), fill = `FDR q-val`)) +
  geom_col() +
  scale_fill_gradient2(midpoint = 0.05) +
  ylab("") + xlab("Normalized Enrichment Score") + ggtitle("Cell Type-adjusted") +
  theme_minimal(base_size = 20) + theme(title = element_text(size = 28), legend.position = "bottom", legend.text = element_text(angle = 45), axis.text.y = element_text(color = "black"))
p2

#theme_minimal(base_size = 20)
```

```{r}
# Get range values for the color bar legend
range <- range(base.graph$`FDR q-val`, pc.graph$`FDR q-val`)
```

```{r}
p1 <- p1 + scale_fill_gradient2(midpoint = 0.05, limits = c(range[1], range[2]))
p1
p2 <- p2 + scale_fill_gradient2(midpoint = 0.05, limits = c(range[1], range[2]))
p2
```

```{r}
p1.legend.plot <- p1 + theme(legend.title = element_text(size = 28), legend.text = element_text(size = 24)) + guides( fill = guide_colorbar(barwidth = 24, barheight = 3))

# Get legend for shared legend
legend <- get_legend(p1.legend.plot)
```

```{r}
panel <- ggarrange(p1, p2, ncol = 2, nrow = 1, labels = "AUTO", font.label = list(size = 24, face = "bold", color = "black"), common.legend = TRUE, legend = "bottom", legend.grob = legend)
ggexport(panel, filename = here("results", "GSE75010", paste0(Sys.Date(), "_limma_gsea.png")), width = 1980, height = 1080)
```   